version: 2.1
jobs:
  compile:
   docker:
      - image: archlinux/base
   steps:
      - run:
          command: |
           pacman -Sy && pacman -S git bc base-devel pahole glibc zip inetutils --needed --noconfirm
           cd;
           git clone https://github.com/Kaz205/android_kernel_google_wahoo -b build --depth=1 -j$(nproc --all)
           git clone https://github.com/Kaz205/arm-none-eabi-gcc --depth=1 -j$(nproc --all)
           git clone https://github.com/Kaz205/aarch64-linux-gnu-gcc --depth=1 -j$(nproc --all)
           git clone https://github.com/Kaz205/AnyKernel3 --depth=1 -j$(nproc --all)
           cd android_kernel_google_wahoo
           ./build_kernel.sh
           mkdir /root/project/out
           cp ~/AnyKernel3/kernel.zip /root/project/out/kernel.zip
          no_output_timeout: 10h

      - store_artifacts:
          path: /root/project/out
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
